create table Event (id identity, 
					title varchar not null,
					description varchar,
					startDate date,
					endDate date,
					startTime time,
					endTime time,
					hashtag varchar,
					createdByUserId bigint,
					modifiedByUserId bigint,
					lastModified timestamp not null,
					primary key (id),
					foreign key (createdByUserId) references User(id),
					foreign key (modifiedByUserId) references User(id));

create table EventSession (id identity,
					eventId bigint,
					title varchar not null,
					description varchar,
					sessionDate date,
					startTime time,
					endTime time,
					hashtag varchar,
					createdByUserId bigint,
					modifiedByUserId bigint,
					lastModified timestamp not null,
					primary key (id),
					foreign key (eventId) references Event(id),
					foreign key (createdByUserId) references User(id),
					foreign key (modifiedByUserId) references User(id));
					
