insert into Member (firstName, lastName, email, password, username, gender, birthdate) values ('Craig', 'Walls', 'cwalls@vmware.com', 'password', 'habuma', 'M', '1977-12-01');
insert into Member (firstName, lastName, email, password, username, gender, birthdate) values ('Keith', 'Donald', 'kdonald@vmware.com', 'password', 'kdonald', 'M', '1977-12-01');
insert into AccountProvider (name, apiKey, secret, requestTokenUrl, authorizeUrl, accessTokenUrl) values ('twitter', 'whatev', 'secret', 'http://www.twitter.com', 'http://www.twitter.com', 'http://www.twitter.com');
insert into AccountProvider (name, apiKey, secret, requestTokenUrl, authorizeUrl, accessTokenUrl) values ('facebook', 'whatev', 'secret', 'http://www.facebook.com', 'http://www.facebook.com', 'http://www.facebook.com');
insert into AccountProvider (name, apiKey, secret, requestTokenUrl, authorizeUrl, accessTokenUrl) values ('linkedin', 'whatev', 'secret', 'http://www.linkedin.com', 'http://www.linkedin.com', 'http://www.linkedin.com');
insert into AccountProvider (name, apiKey, secret, requestTokenUrl, authorizeUrl, accessTokenUrl) values ('tripit', 'whatev', 'secret', 'http://www.tripit.com', 'http://www.tripit.com', 'http://www.tripit.com');
insert into AccountConnection (member, provider, accessToken, accountId) values (1, 'facebook', 'accesstoken', 1);
insert into AccountConnection (member, provider, accessToken) values (1, 'twitter', 'accesstoken');
insert into AccountConnection (member, provider, accessToken) values (1, 'linkedin', 'accesstoken');
insert into AccountConnection (member, provider, accessToken, accountId) values (2, 'facebook', 'accesstoken2', 2);