Welcome to the Greenhouse, $signup.firstName$!

The Greenhouse is where Spring developers connect. Here you'll be able
to hook up with other Spring developers, compare notes, exchange code,
and find out what's going on in the world of Spring development.

You can visit your profile on the Greenhouse by navigating to
http://localhost:8080/greenhouse/members/$signup.userId$.

If you're a Spring developer on-the-go, you'll want to check out our
iPhone app.